//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchhaltung.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuchhaltungDbContext : DbContext
    {
        public BuchhaltungDbContext()
            : base("name=BuchhaltungDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anfangsbetrag> Anfangsbetrag { get; set; }
        public virtual DbSet<Bilanz> Bilanz { get; set; }
        public virtual DbSet<Buchungssatz> Buchungssatz { get; set; }
        public virtual DbSet<Konto> Konto { get; set; }
        public virtual DbSet<KontoArt> KontoArt { get; set; }
    }
}
