//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchhaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchungssatz
    {
        public int Id { get; set; }
        public int SollId { get; set; }
        public int HabenId { get; set; }
        public double Betrag { get; set; }
        public string Beschreibung { get; set; }
        public int BilanzId { get; set; }
    
        public virtual Bilanz Bilanz { get; set; }
        public virtual Konto Haben { get; set; }
        public virtual Konto Soll { get; set; }
    }
}
