//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchhaltung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Konto()
        {
            this.Anfangsbetrag = new HashSet<Anfangsbetrag>();
            this.Haben = new HashSet<Buchungssatz>();
            this.Soll = new HashSet<Buchungssatz>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public string Code { get; set; }
        public int Reihenfolge { get; set; }
        public int KontoArtId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anfangsbetrag> Anfangsbetrag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchungssatz> Haben { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchungssatz> Soll { get; set; }
        public virtual KontoArt KontoArt { get; set; }
    }
}
