CREATE DATABASE Buchhaltung;

CREATE TABLE Bilanz (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Bezeichnung VARCHAR(30) NOT NULL,
	Code VARCHAR(10) NOT NULL UNIQUE,
  Datum DATETIME NOT NULL
);

CREATE TABLE KontoArt (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Bezeichnung VARCHAR(30) NOT NULL,
	Code VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Konto (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Bezeichnung VARCHAR(30) NOT NULL,
	Code VARCHAR(10) NOT NULL UNIQUE,
  Reihenfolge INT NOT NULL,
  KontoArt INT NOT NULL,
  FOREIGN KEY (KontoArt) REFERENCES KontoArt(Id)
);

CREATE TABLE Buchungssatz (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Soll INT NOT NULL,
  Haben INT NOT NULL,
  Betrag FLOAT NOT NULL,
  Beschreibung VARCHAR(250),
  Bilanz INT,
  FOREIGN KEY (Soll) REFERENCES Konto(Id),
  FOREIGN KEY (Haben) REFERENCES Konto(Id),
  FOREIGN KEY (Bilanz) REFERENCES Bilanz(Id)
);

CREATE TABLE Anfangsbetrag (
  Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  Konto INT NOT NULL,
  Betrag FLOAT NOT NULL,
  Bilanz INT NOT NULL,
  FOREIGN KEY (Konto) REFERENCES Konto(Id),
  FOREIGN KEY (Bilanz) REFERENCES Bilanz(Id),
);
